version: "3.7"

services:
    api-php-cli:
        image: ${API_PHP_CLI_IMAGE:-api-php-cli}:${API_PHP_CLI_IMAGE_TAG:-latest}
        build:
            context: ./
            dockerfile: .docker/testing/php-cli/Dockerfile
        depends_on:
            - api-mysql

    api-mysql:
        image: docker.io/bitnami/mysql:8.0-debian-10
        hostname: mysql
        environment:
            MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is not set or empty}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
            MARIADB_CHARACTER_SET: ${MYSQL_CHARACTER_SET:-utf8mb4}
            MARIADB_COLLATE: ${MYSQL_COLLATE:-utf8mb4_general_ci}
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-root}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is not set or empty}
            MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE is not set or empty}
            MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTH_PLUGIN:-mysql_native_password}
